services:
  service:
#    build:
#      #Go back one directory
#      context: ..
#      dockerfile: docker/Dockerfile
    image: michaelkimani/whitepointinventoryservice:latest
    container_name: whitepointinventoryservice-container
    #Exposed api ports
    ports:
      - "8080:8080"
    #Set environment for the service - i.e. used in the go code
    environment:
      - "DB_URL=postgres://postgres:novek@db:5432/whitepointinventory?sslmode=disable"
      - "PORT=8080"
    depends_on:
      - db
      - migrate

  db:
    image: postgres:13-alpine
    container_name: whitepointinventorydb-container
    #Exposed db ports - in case one needs to use pgAdmin or a similar client
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: novek
      POSTGRES_DB: whitepointinventory
    volumes:
      - postgres-data:/var/lib/postgresql/data

  migrate:
    image: michaelkimani/whitepointinventorymigrations
#    build:
#      #Go back one directory
#      context: ..
#      dockerfile: docker/Dockerfile.migrate
    container_name: whitepointinventorymigrations-container
    command: ["./run_migrations.sh"]
    depends_on:
      - db

volumes:
  postgres-data:




